name: build for macOS 10.9-10.14

on:
  workflow_dispatch:

jobs:
  build:
    name: build Momiji
    runs-on: macos-15
    steps:     
      - name: Checkout source code
        id: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      # Restore cached toolchains and build artifacts
      - name: Restore sccache cache mozbuild toolchains
        id: restore-cache
        uses: actions/cache/restore@v5.0.4
        with:
          path: | 
            ~/Library/Caches/Mozilla.sccache 
            ~/.mozbuild
          key: ${{ runner.os }}-lld-${{ hashFiles('mozconfig-cicd.sh') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-lld-${{ hashFiles('mozconfig-cicd.sh') }}
            ${{ runner.os }}-lld

      - name: Select Xcode 16.3 (SDK 15.4)
        run: sudo xcode-select -s /Applications/Xcode_16.3.app/Contents/Developer

      - name: Bootstrapping build deps
        id: bootstrap
        run: |
          if [ ! -d "$HOME/.mozbuild" ]; then
            echo "Cached .mozbuild toolchain not found. Starting bootstrap..."
            /usr/bin/python3 ./mach bootstrap --application-choice=browser
        
            # Tạo thư mục tạm để lưu các toolchain quan trọng
            mkdir -p ~/tmp_toolchains
            
            # Di chuyển các thư mục cần thiết ra ngoài (dùng -f để tránh hỏi)
            [ -d "$HOME/.mozbuild/node" ] && mv "$HOME/.mozbuild/node" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sccache" ] && mv "$HOME/.mozbuild/sccache" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/cbindgen" ] && mv "$HOME/.mozbuild/cbindgen" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/clang" ] && mv "$HOME/.mozbuild/clang" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sysroot-wasm32-wasi" ] && mv "$HOME/.mozbuild/sysroot-wasm32-wasi" ~/tmp_toolchains/
            
            # Xóa sạch toàn bộ thư mục .mozbuild cũ (vốn chứa nhiều rác)
            rm -rf "$HOME/.mozbuild"
        
            # Đổi tên thư mục tạm thành .mozbuild
            mv ~/tmp_toolchains "$HOME/.mozbuild"
            
            # echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, nasm, dump_syms, clang, sysroot-wasm32-wasi"
            echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, clang, sysroot-wasm32-wasi"
          fi

          # Install nasm from Homebrew
          brew install nasm

      - name: Create mozconfig build config from template
        id: buildcfg-link
        run: ln -sf ./mozconfig-cicd_1009-1014.sh mozconfig
    
      - name: Manually configure Rust toolchain
        id: rust-cfg
        run: |
          if [ ! -d "$HOME/.rustup/toolchains/1.91.0-custom" ]; then
            echo "Cached Rust 1.91.0-custom-cross not found. Starting bootstrap..."
            curl -L https://github.com/aobaharuki2005/rust/releases/download/v1.91.0-custom-arm64cross/1.91.0-custom-cross.tar.gz -o 1.91.0-custom-cross.tar.gz
            mkdir -p ~/.rustup/toolchains
            tar -xf ./1.91.0-custom-cross.tar.gz -C ~/.rustup/toolchains
            echo "Bootstrap Rust 1.91.0-custom-cross finished."
          fi
        
          # Change default Rust toolchain
          rustup default 1.91.0-custom-cross
          rustup override set 1.91.0-custom-cross

          # Verify Rust installation
          cargo --version
          rustc --version
          
      - name: Configure build options
        id: configure
        run: /usr/bin/python3 ./mach configure

      - name: Build
        id: build
        run: /usr/bin/python3 ./mach build

      - name: End sccache session
        id: stop-sccache
        run: sleep 60 && $HOME/.mozbuild/sccache/sccache --stop-server

      - name: Export the DMG image
        id: pkg
        run: /usr/bin/python3 ./mach package

      # path to built app: obj-ff-dbg-esr/dist/*.dmg
      - name: Polyfill & Repackage
        id: polyfill-and-repkg
        run: |
          # Get the current Momiji version
          export VERSION=$(cat browser/config/version.txt)
        
          # Copy Momiji.app to /tmp
          hdiutil attach "obj-ff-dbg-esr/dist/firefox-${VERSION}.en-US.mac.dmg"
          cp -R /Volumes/Nightly/Nightly.app /tmp

          # Changedir to /tmp and package 10.12-10.14 distribution
          cd /tmp
          zip -qr "Nightly-${VERSION}_macOS10.12-10.14.zip" Nightly.app
          
          # Build libMacportsLegacySystem.B.dylib (patched to support CCRandomGenerateBytes)
          git clone --recursive --branch 1.5.2_addCCRandom https://github.com/aobaharuki2005/macports-legacy-support.git
          cd macports-legacy-support


          CC="clang --target=x86_64-apple-macos10.6" \
          CXX="clang++ --target=x86_64-apple-macos10.6" \
          CFLAGS="-Os" \
          CXXFLAGS="-Os" \
          LDFLAGS="--target=x86_64-apple-macos10.6" \
          make
          
          # copy libMacportsLegacySystem.B.dylib to the Frameworks directory of Momiji.app
          cp lib/libMacportsLegacySystem.B.dylib /tmp/Nightly.app/Contents/MacOS

          # Polyfill XUL, libmozavutil.dylib and libgkcodecs.dylib
          cd /tmp/Nightly.app/Contents/MacOS/
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "XUL"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libmozavutil.dylib"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libgkcodecs.dylib"

          # Package the 10.9-10.11 distribution (MUST CHANGE DIRECTORY to /tmp FIRST)
          cd /tmp
          zip -qr "Nightly-${VERSION}_macOS10.9-10.11.zip" Nightly.app

      - name: Saving cache even if pipeline fails
        id: save-cache
        if: always()
        uses: actions/cache/save@v5.0.4
        with:
          key: ${{ runner.os }}-lld-${{ hashFiles('mozconfig-cicd.sh') }}-${{ github.run_id }}
          path: |
            ~/Library/Caches/Mozilla.sccache 
            ~/.mozbuild

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v7.0.0
        with:
          archive: true
          path: |
            /tmp/*.zip
            obj-ff-dbg-esr/dist/firefox-*.en-US.mac.dmg
          if-no-files-found: error
          retention-days: 7
    
