name: build Momiji testing distribution

on:
  push:
    branches:
      - '140.1.X*'
  workflow_dispatch:

jobs:
  build:
    name: build Momiji
    runs-on: macos-15-intel
    steps:     
      - name: Checkout source code
        id: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      # Khôi phục cache của sccache từ các lần build trước
      - name: Restore sccache cache
        uses: actions/cache@v5.0.4
        with:
          path: ~/Library/Caches/Mozilla.sccache
          key: ${{ runner.os }}-sccache-${{ github.sha }}  # == *macos-15-intel*-sccache-*session-sha*
          restore-keys: |
            ${{ runner.os }}-sccache-

      - name: Bootstrapping build deps
        id: bootstrap
        run: /usr/bin/python3 ./mach bootstrap --application-choice=browser

      - name: Create mozconfig build config from template
        id: buildcfg-link
        run: ln -sf ./mozconfig-cicd.sh mozconfig

      - name: Manually configure Rust toolchain
        id: rust-cfg
        run: |
          curl -L https://github.com/aobaharuki2005/rust/releases/download/v1.91.0-custom-redist/1.91.0-custom.tar.gz -o 1.91.0-custom.tar.gz
          mkdir -p ~/.rustup/toolchains
          tar -xf ./1.91.0-custom.tar.gz -C ~/.rustup/toolchains
        
          # Change default Rust toolchain
          rustup default 1.91.0-custom
          rustup override set 1.91.0-custom

          # Verify Rust installation
          cargo --version
          rustc --version

      - name: Configure build options
        id: configure
        run: | 
          # Khởi động sccache trước khi build
          $HOME/.mozbuild/sccache/sccache --start-server
          /usr/bin/python3 ./mach configure

      - name: Build
        id: build
        run: /usr/bin/python3 ./mach build

      - name: Show sccache stats
        id: show-sccache-stats
        run: $HOME/.mozbuild/sccache/sccache --show-stats

      - name: Package
        id: pkg
        run: /usr/bin/python3 ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: momiji-build-output
          path: obj-ff-dbg-esr/dist/*.dmg
          if-no-files-found: error
          retention-days: 7
    
